config/routes.rb
Rails.application.routes.draw do

  get 'items/index' => 'items#index'
  get "items/about" => "items#about", as: "about"
  get "items/tag_index" => "items#tag_index"
  get "search_tag"=>"items#search_tag"

  root to: "items#index"

  devise_for :admins
  devise_for :users

  resources :items, only: [:new, :index, :show, :edit, :create, :destroy]do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :customers, only: [:index, :show, :edit]
  resources :users, only: [:show, :edit, :update, :index]

  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :item_tags,dependent: :destroy
  has_many :tags,through: :item_tags

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_item_tag = Tag.find_or_create_by(name: new)
      self.tags << new_item_tag
   end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def top
  end

  def about
  end

  def index
    @items = Item.page(params[:page]).per(10)
    @tag_list=Tag.all
  end

  def show
    @item = Item.find(params[:id])
    @post_comment = PostComment.new
    @item_tags = @item.tags
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    # 受け取った値を,で区切って配列にする
    tag_list=params[:item][:name].split(',')
    if @item.save
      @item.save_tag(tag_list)
      redirect_to items_path,notice:'投稿完了!'
    else
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, notice: "successfully delete"
  end

  def edit
  end

  def search_tag
    # 検索結果画面でもタグ一覧表示
    @tag_list=Tag.all
    # 検索されたタグを受け取る
    @tag=Tag.find(params[:tag_id])
    # 検索されたタグに紐づく投稿を表示
    @items=@tag.items.page(params[:page]).per(10)
  end

  def tag_index
    @tag_list=Tag.all
  end

  private

  def item_params
    params.require(:item).permit(:title, :image, :body)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error.html.erb
<% if errors.errors.any? %>
  <%= errors.errors.count %>件のエラーが発生しました
  <ul>
    <% errors.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/items/_favorited.html.erb
<!--いいね-->
<% if user_signed_in? %>
  <% if item.favorited_by?(current_user) %>
    <p>
      <%= link_to item_favorites_path(item), method: :delete do %>
        ♥<%= item.favorites.count %> いいね
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to item_favorites_path(item), method: :post do %>
        ♡<%= item.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/items/_list.html.erb
<!--投稿一覧-->
<% items.each do |item| %>
<!--投稿はカードで囲む-->
<div class="card">
  <div class="card-body">
    <h6 class="card-title">

  <%= link_to item_path(item.id) do %>
  <% if item.image.attached? %>
    <%= image_tag item.image, size:"200x200" %>
  <% end %>
  <p><%= item.title %></p>
  <p><%= item.body %></p>
  <p><%= link_to "#{item.post_comments.count} コメント", item_path(item.id) %></p>
  <p><%= image_tag item.user.get_profile_image, size:"50x50" %></p>
  <p><%= item.user.name %></p>
  <% end %>

    </h6>
  </div>
</div>
<% end %>
<%= paginate items %>

app/views/items/_tag.html.erb
<!--タグリスト-->
<% tag_list.each do |list|%>
  <%=link_to list.name,search_tag_path(tag_id: list.id) %>
  <%="(#{list.items.count})" %>
<% end %>

app/views/items/about.html.erb
<div class="container">
  <div class="row">

    <div class="center-block">

    </div>
    <h1 class="text-center">ここはオタク収納があふれかえるサイト・・・</h1>
    <h1 class="text-center">ここで沢山の出会いをしてください！</h1>

  </nav>
</nav>

app/views/items/index.html.erb
<h1>投稿一覧</h1>
<%= render partial:  'list', locals: { tag_list: @tag_list, items: @items } %>

app/views/items/new.html.erb
<h1>新規投稿</h1>

<!--エラーメッセージ-->
<%= render 'error', errors: @item %>

<%= form_with model: @item do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>内容</h4>
  <%= f.text_area :body %>

  <h4><%= f.label"タグ (,で区切ると複数タグ登録できます)" %></h4>
  <%= f.text_field :name,value: @tag_list,class:"form-control"%>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <%= f.submit '投稿' %>

<% end %>

app/views/items/search_tag.html.erb
<h5>タグが<%=@tag.name%>の投稿一覧</h5>

<!--タグリスト-->
<% @tag_list.each do |list|%>
<%=link_to list.name,search_tag_path(tag_id: list.id) %>
<%="(#{list.items.count})" %>
<% end %>

<% @items.each do |item| %>

<div class="row">


  <!--投稿はカードで囲む-->
  <div class="col-lg-12 card">
    <div class="card-body">
      <h6 class="card-title">
        <%=link_to item_path(item.id) do %>

          <%= item.title %><br>
          <div class="col-lg-4">
          <% if item.image.attached? %>
            <%= image_tag item.image, size:"300x300" %>
          <% end %>
          </div>
          <div class="col-lg-8">
          <p><%= item.body %></p>
          <p>
            <%= render 'items/favorited', item: item %>
            <%= "#{item.post_comments.count} コメント" %>
          </p>
          <p><%= image_tag item.user.get_profile_image, size:"50x50" %><%= item.user.name %></p>
          </div>
        <% end %>
      </h6>
    </div>
  </div>


</div>
<% end %>

<div class="pagination pagination-sm justify-content-center">
  <%= paginate @items %>
</div>

app/views/items/show.html.erb
<h1>投稿詳細</h1>
<div>

  <% @item_tags.each do |tag| %>
    <%= link_to tag.name,search_tag_path(tag_id: tag.id)%>
    <%="(#{tag.items.count})" %>
  <% end %>

  <% if @item.image.attached? %>
    <p><%= image_tag @item.image, size:"200x200" %></p>
  <% end %>
  <p><%= @item.title %></p>
  <p><%= @item.body %></p>
  <p><%= image_tag @item.user.get_profile_image, size:"100x100" %></p>
  <p><%= @item.user.name %></p>
  <p>投稿日：<%= @item.created_at.strftime('%Y/%m/%d') %></p>

  <% if @item.user == current_user || admin_signed_in? %>
    <%= link_to "削除", item_path(@item), method: :delete %>
  <% end %>

</div>

<div>

  <!--コメント-->
  <p>コメント件数：<%= @item.post_comments.count %></p>
  <% @item.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image, size:"100x100" %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <!--コメント削除-->
    <% if post_comment.user == current_user || admin_signed_in? %>
      <%= link_to "削除", item_post_comment_path(post_comment.item, post_comment), method: :delete %>
    <% end %>
  <% end %>

    <!--いいね-->
    <%= render 'items/favorited', item: @item %>

</div>
<div>
  <%= form_with model: [@item, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/items/tag_index.html.erb
<!--タグリスト-->
<h4>タグ一覧</h4>
<% @tag_list.each do |list|%>
<%=link_to list.name,search_tag_path(tag_id: list.id) %>
<%="(#{list.items.count})" %>
<% end %>

app/views/items/top.html.erb
<h1>Items#top</h1>