config/routes.rb
Rails.application.routes.draw do

  get 'items/index' => 'items#index'
  get "items/about" => "items#about", as: "about"
  get "items/tag_index" => "items#tag_index"
  get "search_tag"=>"items#search_tag"

  root to: "items#index"

  devise_for :admins
  devise_for :users

  resources :items, only: [:new, :index, :show, :edit, :create, :destroy]do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :customers, only: [:index, :show, :edit]
  resources :users, only: [:show, :edit, :update, :index]

  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #":registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :item

end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :item_tags,dependent: :destroy
  has_many :tags,through: :item_tags

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_item_tag = Tag.find_or_create_by(name: new)
      self.tags << new_item_tag
   end
  end

end

app/models/item_tag.rb
class ItemTag < ApplicationRecord
  belongs_to :item
  belongs_to :tag

  validates :item_id, presence: true
  validates :tag_id, presence: true



end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :item

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :item_tags,dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿を持つ　それは、post_tagsを通じて参照できる
  has_many :items,through: :item_tags

  validates :name, uniqueness: true, presence: true

  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    favorite = current_user.favorites.new(item_id: item.id)
    favorite.save
    redirect_to item_path(item)
  end

  def destroy
    item = Item.find(params[:item_id])
    favorite = current_user.favorites.find_by(item_id: item.id)
    favorite.destroy
    redirect_to item_path(item)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def top
  end

  def about
  end

  def index
    @items = Item.page(params[:page]).per(10)
    @tag_list=Tag.all
  end

  def show
    @item = Item.find(params[:id])
    @post_comment = PostComment.new
    @item_tags = @item.tags
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    # 受け取った値を,で区切って配列にする
    tag_list=params[:item][:name].split(',')
    if @item.save
      @item.save_tag(tag_list)
      redirect_to items_path,notice:'投稿完了!'
    else
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, notice: "successfully delete"
  end

  def edit
  end

  def search_tag
    # 検索結果画面でもタグ一覧表示
    @tag_list=Tag.all
    # 検索されたタグを受け取る
    @tag=Tag.find(params[:tag_id])
    # 検索されたタグに紐づく投稿を表示
    @items=@tag.items.page(params[:page]).per(10)
  end

  def tag_index
    @tag_list=Tag.all
  end

  private

  def item_params
    params.require(:item).permit(:title, :image, :body)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_path(item)
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to item_path(params[:item_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items.page(params[:page]).per(10)
    @tag_list=Tag.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.page(params[:page]).per(10)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def withdrawal
    @user = User.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:is_deleted)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">

    


    <% if user_signed_in? %><!--顧客ログイン-->

      <li class="list-unstyled">
        <%= link_to "マイページ", user_path(current_user.id),class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "新規投稿", new_item_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "投稿一覧", items_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "タグ一覧", items_tag_index_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'btn btn-sm btn-outline-dark m-3'  %>
      </li>

    <% elsif admin_signed_in? %><!--管理者ログイン-->

      <li class="list-unstyled">
        <%= link_to "会員一覧", users_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "投稿一覧", items_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "タグ一覧", items_tag_index_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'btn btn-sm btn-outline-dark m-3'  %>
      </li>

    <% else %><!--ログイン前-->

      <li class="list-unstyled">
        <%= link_to "About", about_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "投稿一覧", items_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "タグ一覧", items_tag_index_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "新規登録", new_user_registration_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>
      <li class="list-unstyled">
        <%= link_to "ログイン", new_user_session_path,class: 'btn btn-sm btn-outline-dark m-3' %>
      </li>

    <% end %>



  </nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100 background-color: rgb(237, 247, 255);">

    <header  class="skin-bgHeader border-bottom pull-right">
      <%= render 'layouts/header' %>
    </header>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>